import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    home: 'Home',
    cakes: 'Cakes',
    about: 'About',
    contact: 'Contact',
    orderNow: 'Order Now',
    exploreCakes: 'Explore Cakes',
    designUniqueCake: 'Design Your Cake',
    popularCakes: 'Popular Cakes',
    viewAll: 'View All',
    searchPlaceholder: 'Search cakes...',
    whyChooseUs: 'Why choose us?',
    premiumIngredients: 'Premium Ingredients',
    premiumIngredientsSub: 'Only the best goes into our cakes',
    customOrders: 'Custom Orders',
    customOrdersSub: 'Personalise your cake just the way you want',
    hygienicSafe: 'Hygienic & Safe',
    hygienicSafeSub: 'Clean and safe baking practices',
    timelyDelivery: 'Timely Pickup',
    timelyDeliverySub: 'Fresh cakes, ready on time',
    heroTitleMain: 'Home-baked with',
    heroTitleHighlight: 'love',
    heroSubtextFallback: 'Artisanal, 100% vegetarian cakes crafted for your special moments.',
    feat1Title: '100% Vegetarian',
    feat1Sub: 'Pure & delicious',
    feat2Title: 'Made with Love',
    feat2Sub: 'From our kitchen to yours',
    feat3Title: 'Freshly Baked',
    feat3Sub: 'On time, every time',
    heroSideTitle: 'Cakes<br/>for every<br/>occasion',
    heroSideSub: "Birthdays, anniversaries, celebrations or just because — we've got you covered.",
    aboutStoryTitle: 'A little story about PR Cake',
    aboutStoryText: 'We started PR Cake with a simple idea — to bring happiness through homemade, vegetarian cakes made from quality ingredients. Every cake is baked fresh, with care, so your special moments become a little sweeter.',
    ourStory: 'Our Story',
    whatCustomersSay: 'What our customers say',
    noReviews: 'Check back soon for customer reviews.',
    stayUpdated: 'Stay updated with our latest cakes and offers',
    subscribe: 'Subscribe',
    emailPlaceholder: 'Enter your email',
    basePrice: 'Base Price',
    addToCart: 'Add to Cart',
    chooseLanguage: 'Choose your language',
    yourCart: 'Your Cart',
    total: 'Total',
    confirmOrder: 'Confirm Order',
    selectWeight: 'Select Weight',
    step: 'Step',
    next: 'Next',
    messageOptional: 'Message on Cake (Optional)',
    cartEmpty: 'Your cart is empty',
    cartEmptySubtext: "Looks like you haven't added any delicious cakes yet.",
    startShopping: 'Start Shopping',
    all: 'All',
    bestSeller: 'Best Seller',
    birthday: 'Birthday',
    trending: 'Trending',
    seasonal: 'Seasonal',
    others: 'Others',
    offers: 'Offers',
    noCakesFound: 'No cakes found',
    noCakesSubtext: "We couldn't find any active cakes in this category right now. Try checking another tab!",
    addonsAndMessage: 'Add-ons & Message',
    included: 'Included',
    qty: 'Qty',
    subtotal: 'Subtotal',
    yourName: 'Your Name',
    phoneNumber: 'Phone Number',
    date: 'Date',
    time: 'Time',
    of: 'of',
    ourCakes: 'Our Cakes',
    shopBannerSubtext: 'Freshly baked, 100% vegetarian cakes for every occasion.',
    customCakes: 'Custom cakes?',
    customCakesSub: "Tell us your idea and we'll make it happen.",
    requestCustomCake: 'Request Custom Cake',
    products: 'products',
    sortBy: 'Sort by',
    popular: 'Popular',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    filter: 'Filter',
    clearAll: 'Clear All',
    priceRange: 'Price Range',
    cakeType: 'Cake Type',
    chocolate: 'Chocolate',
    fruit: 'Fruit',
    premium: 'Premium',
    occasion: 'Occasion',
    anniversary: 'Anniversary',
    weight: 'Weight',
    flavour: 'Flavour',
    dietaryPreference: 'Dietary Preference',
    viewDetails: 'View Details',
    safeHygienic: 'Safe & Hygienic',
    safeHygienicSub: 'Clean baking practices',
    madeWithLove: 'Made with Love',
    madeWithLoveSub: 'For your special moments',
    buildCustomCake: 'Build Custom Cake',
    step1Base: 'Select Base',
    step2Weight: 'Select Weight',
    step3Design: 'Select Design',
    step4Addons: 'Add-ons',
    step5Date: 'Delivery / Pickup Date',
    customDesign: 'Custom Design',
    uploadImage: 'Upload Image',
    uploading: 'Uploading...',
    priceToBeQuoted: 'Price: To be quoted',
    customQuoteReq: 'Please review my custom design and provide a quote.',
    chocolate: 'Chocolate',
    vanilla: 'Vanilla',
    pineapple: 'Pineapple',
    cheeseCake: 'Cheese Cake',
    nonEdibleToppers: 'Non-edible printed toppers',
    edibleToppers: 'Edible toppers',
    fondantFinish: 'Fondant finish',
    deliveryDate: 'Delivery Date',
    stdDesign: 'Standard Design',
    fruit: 'Fruit',
    premium: 'Premium',
    others: 'Others',
    regular: 'Regular',
    birthday: 'Birthday',
    anniversary: 'Anniversary',
    wedding: 'Wedding',
    all: 'All',
    homemadeCakesForEveryCelebration: 'Homemade Cakes for Every Celebration',
    madeWithRealIngredients: 'Made with real ingredients, pure love and a touch of happiness.',
    customizeYourCake: 'Customize Your Cake',
    storePickupOnly: 'Store Pickup Only',
    noDelivery: 'No Delivery',
    chooseBaseFlavour: 'Choose the base, flavour, frosting, toppings and more.',
    startCustomizing: 'Start Customizing',
    freshlyBaked: 'FRESHLY BAKED',
    hundredPercentVeg: '100% VEGETARIAN',
    savedDetails: 'Saved Details',
    defaultName: 'Default Name',
    defaultWhatsApp: 'Default WhatsApp Number',
    saveOnThisDevice: 'Save on this Device',
    savedDetailsHelper: 'Your details are saved on this device for faster checkout. No account creation required.',
    noCakesMatching: 'No cakes found matching',
    clearSearch: 'Clear Search',
    savedStatus: 'Saved',
    savedDetailsSuccess: 'Your details have been saved on this device.',
    review: 'Review',
    reviews: 'Reviews',
    noReviewsYet: 'No reviews yet',
    customerReviews: 'Customer Reviews',
    cancel: 'Cancel',
    writeReview: 'Write a Review',
    yourName: 'Your Name',
    rating: 'Rating',
    yourReview: 'Your Review',
    submitting: 'Submitting...',
    submitReview: 'Submit Review',
    noReviewsSubtext: 'Be the first to review this delicious cake!',
    reviewSubmitted: 'Review submitted successfully!',
    reviewError: 'Error submitting review'
  },
  gu: {
    home: 'ઘર',
    cakes: 'કેક',
    about: 'વિશે',
    contact: 'સંપર્ક કરો',
    orderNow: 'હમણાં ઓર્ડર કરો',
    exploreCakes: 'કેક અન્વેષણ કરો',
    designUniqueCake: 'તમારી કેક ડિઝાઇન કરો',
    popularCakes: 'લોકપ્રિય કેક',
    viewAll: 'બધા જુઓ',
    searchPlaceholder: 'કેક શોધો...',
    whyChooseUs: 'અમને કેમ પસંદ કરો?',
    premiumIngredients: 'શ્રેષ્ઠ સામગ્રી',
    premiumIngredientsSub: 'અમારી કેકમાં માત્ર શ્રેષ્ઠ જ જાય છે',
    customOrders: 'કસ્ટમ ઓર્ડર',
    customOrdersSub: 'તમારી કેકને તમારી ઇચ્છા મુજબ બનાવો',
    hygienicSafe: 'સ્વચ્છ અને સુરક્ષિત',
    hygienicSafeSub: 'સ્વચ્છ અને સુરક્ષિત પકવવાની પદ્ધતિઓ',
    timelyDelivery: 'સમયસર પિકઅપ',
    timelyDeliverySub: 'તાજી કેક, સમયસર તૈયાર',
    heroTitleMain: 'ઘરે બનાવેલ',
    heroTitleHighlight: 'પ્રેમથી',
    heroSubtextFallback: 'તમારી ખાસ ક્ષણો માટે બનાવેલ કલાત્મક, 100% શાકાહારી કેક.',
    feat1Title: '100% શાકાહારી',
    feat1Sub: 'શુદ્ધ અને સ્વાદિષ્ટ',
    feat2Title: 'પ્રેમથી બનાવેલ',
    feat2Sub: 'અમારા રસોડામાંથી તમારા સુધી',
    feat3Title: 'તાજી પકવેલી',
    feat3Sub: 'સમયસર, દરેક વખતે',
    heroSideTitle: 'દરેક<br/>પ્રસંગ<br/>માટે કેક',
    heroSideSub: 'જન્મદિવસ, વર્ષગાંઠ, ઉજવણી અથવા એમ જ - અમે તમારી સાથે છીએ.',
    aboutStoryTitle: 'PR Cake વિશે એક નાની વાર્તા',
    aboutStoryText: 'અમે PR Cake ની શરૂઆત એક સરળ વિચાર સાથે કરી હતી - ગુણવત્તાયુક્ત સામગ્રીમાંથી બનેલી હોમમેઇડ, શાકાહારી કેક દ્વારા ખુશી લાવવા. દરેક કેક તાજી પકવવામાં આવે છે, કાળજી સાથે, જેથી તમારી ખાસ ક્ષણો થોડી વધુ મીઠી બને.',
    ourStory: 'અમારી વાર્તા',
    whatCustomersSay: 'અમારા ગ્રાહકો શું કહે છે',
    noReviews: 'ગ્રાહક સમીક્ષાઓ માટે ટૂંક સમયમાં પાછા તપાસો.',
    stayUpdated: 'અમારી નવીનતમ કેક અને ઑફર્સ સાથે અપડેટ રહો',
    subscribe: 'સબ્સ્ક્રાઇબ કરો',
    emailPlaceholder: 'તમારો ઇમેઇલ દાખલ કરો',
    basePrice: 'મૂળ કિંમત',
    addToCart: 'કાર્ટમાં ઉમેરો',
    chooseLanguage: 'તમારી ભાષા પસંદ કરો',
    yourCart: 'તમારું કાર્ટ',
    total: 'કુલ',
    confirmOrder: 'ઓર્ડર કન્ફર્મ કરો',
    selectWeight: 'વજન પસંદ કરો',
    step: 'પગલું',
    next: 'આગળ',
    messageOptional: 'કેક પર સંદેશ (વૈકલ્પિક)',
    cartEmpty: 'તમારું કાર્ટ ખાલી છે',
    cartEmptySubtext: "એવું લાગે છે કે તમે હજી સુધી કોઈ સ્વાદિષ્ટ કેક ઉમેરી નથી.",
    startShopping: 'ખરીદી શરૂ કરો',
    all: 'બધા',
    bestSeller: 'શ્રેષ્ઠ વેચાણ',
    birthday: 'જન્મદિવસ',
    trending: 'ટ્રેન્ડિંગ',
    seasonal: 'મોસમી',
    others: 'અન્ય',
    offers: 'ઓફર',
    noCakesFound: 'કોઈ કેક મળી નથી',
    noCakesSubtext: "અમને અત્યારે આ કેટેગરીમાં કોઈ સક્રિય કેક મળી નથી. અન્ય ટૅબ તપાસવાનો પ્રયાસ કરો!",
    addonsAndMessage: 'એડ-ઓન અને સંદેશ',
    included: 'શામેલ છે',
    qty: 'માત્રા',
    subtotal: 'પેટા સરવાળો',
    yourName: 'તમારું નામ',
    phoneNumber: 'ફોન નંબર',
    date: 'તારીખ',
    time: 'સમય',
    of: 'માંથી',
    ourCakes: 'અમારી કેક',
    shopBannerSubtext: 'દરેક પ્રસંગ માટે તાજી પકવેલી, 100% શાકાહારી કેક.',
    customCakes: 'કસ્ટમ કેક?',
    customCakesSub: 'અમને તમારો વિચાર કહો અને અમે તેને સાકાર કરીશું.',
    requestCustomCake: 'કસ્ટમ કેકની વિનંતી કરો',
    products: 'ઉત્પાદનો',
    sortBy: 'ક્રમમાં ગોઠવો',
    popular: 'લોકપ્રિય',
    priceLowHigh: 'કિંમત: ઓછી થી વધુ',
    priceHighLow: 'કિંમત: વધુ થી ઓછી',
    filter: 'ફિલ્ટર',
    clearAll: 'બધા સાફ કરો',
    priceRange: 'કિંમત શ્રેણી',
    cakeType: 'કેકનો પ્રકાર',
    chocolate: 'ચોકલેટ',
    fruit: 'ફળ',
    premium: 'પ્રીમિયમ',
    occasion: 'પ્રસંગ',
    anniversary: 'વર્ષગાંઠ',
    weight: 'વજન',
    flavour: 'સ્વાદ',
    dietaryPreference: 'આહાર પ્રાધાન્યતા',
    viewDetails: 'વિગતો જુઓ',
    safeHygienic: 'સુરક્ષિત અને સ્વચ્છ',
    safeHygienicSub: 'સ્વચ્છ પકવવાની પદ્ધતિઓ',
    madeWithLove: 'પ્રેમથી બનાવેલ',
    madeWithLoveSub: 'તમારી ખાસ ક્ષણો માટે',
    buildCustomCake: 'કસ્ટમ કેક બનાવો',
    step1Base: 'બેઝ પસંદ કરો',
    step2Weight: 'વજન પસંદ કરો',
    step3Design: 'ડિઝાઇન પસંદ કરો',
    step4Addons: 'એડ-ઓન્સ',
    step5Date: 'ડિલિવરી / પિકઅપ તારીખ',
    customDesign: 'કસ્ટમ ડિઝાઇન',
    uploadImage: 'છબી અપલોડ કરો',
    uploading: 'અપલોડ થઈ રહ્યું છે...',
    priceToBeQuoted: 'કિંમત: ક્વોટ કરવામાં આવશે',
    customQuoteReq: 'કૃપા કરીને મારી કસ્ટમ ડિઝાઇન જુઓ અને કિંમત આપો.',
    chocolate: 'ચોકલેટ',
    vanilla: 'વેનીલા',
    pineapple: 'પાઇનેપલ',
    cheeseCake: 'ચીઝ કેક',
    nonEdibleToppers: 'નોન-એડિબલ પ્રિન્ટેડ ટોપર્સ',
    edibleToppers: 'એડિબલ ટોપર્સ',
    fondantFinish: 'ફોન્ડન્ટ ફિનિશ',
    deliveryDate: 'ડિલિવરી તારીખ',
    stdDesign: 'સ્ટાન્ડર્ડ ડિઝાઇન',
    fruit: 'ફળ',
    premium: 'પ્રીમિયમ',
    others: 'અન્ય',
    regular: 'નિયમિત',
    birthday: 'જન્મદિવસ',
    anniversary: 'વર્ષગાંઠ',
    wedding: 'લગ્ન',
    all: 'બધા',
    homemadeCakesForEveryCelebration: 'દરેક ઉજવણી માટે ઘરે બનાવેલ કેક',
    madeWithRealIngredients: 'અસલ સામગ્રી, શુદ્ધ પ્રેમ અને ખુશીના સ્પર્શથી બનાવેલ.',
    customizeYourCake: 'તમારી કેક કસ્ટમાઇઝ કરો',
    storePickupOnly: 'ફક્ત સ્ટોર પિકઅપ',
    noDelivery: 'કોઈ હોમ ડિલિવરી નથી',
    chooseBaseFlavour: 'બેઝ, ફ્લેવર, ફ્રોસ્ટિંગ, ટોપિંગ્સ અને બીજું ઘણું પસંદ કરો.',
    startCustomizing: 'કસ્ટમાઇઝ કરવાનું શરૂ કરો',
    freshlyBaked: 'તાજું પકવેલું',
    hundredPercentVeg: '100% શાકાહારી',
    savedDetails: 'સાચવેલી વિગતો',
    defaultName: 'ડિફૉલ્ટ નામ',
    defaultWhatsApp: 'ડિફૉલ્ટ WhatsApp નંબર',
    saveOnThisDevice: 'આ ઉપકરણ પર સાચવો',
    savedDetailsHelper: 'ઝડપી ચેકઆઉટ માટે તમારી વિગતો આ ઉપકરણ પર સાચવવામાં આવી છે. કોઈ એકાઉન્ટ બનાવવાની જરૂર નથી.',
    noCakesMatching: 'કોઈ કેક મળી નથી જે મેળ ખાતી હોય',
    clearSearch: 'શોધ સાફ કરો',
    savedStatus: 'સાચવ્યું',
    savedDetailsSuccess: 'તમારી વિગતો આ ઉપકરણ પર સાચવવામાં આવી છે.',
    review: 'સમીક્ષા',
    reviews: 'સમીક્ષાઓ',
    noReviewsYet: 'હજી સુધી કોઈ સમીક્ષાઓ નથી',
    customerReviews: 'ગ્રાહક સમીક્ષાઓ',
    cancel: 'રદ કરો',
    writeReview: 'સમીક્ષા લખો',
    yourName: 'તમારું નામ',
    rating: 'રેટિંગ',
    yourReview: 'તમારી સમીક્ષા',
    submitting: 'સબમિટ થઈ રહ્યું છે...',
    submitReview: 'સમીક્ષા સબમિટ કરો',
    noReviewsSubtext: 'આ સ્વાદિષ્ટ કેકની સમીક્ષા કરનાર પ્રથમ બનો!',
    reviewSubmitted: 'સમીક્ષા સફળતાપૂર્વક સબમિટ થઈ!',
    reviewError: 'સમીક્ષા સબમિટ કરવામાં ભૂલ'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(null);
  const [hasSelected, setHasSelected] = useState(true);

  useEffect(() => {
    const saved = localStorage.getItem('prCakeLang');
    if (saved) {
      setLanguage(saved);
      setHasSelected(true);
    } else {
      setLanguage('en'); // default internally before selection
      setHasSelected(false);
    }
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    setHasSelected(true);
    localStorage.setItem('prCakeLang', lang);
  };

  const t = (key) => {
    const fallback = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
    return translations[language]?.[key] || translations['en'][key] || fallback;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, hasSelected }}>
      {children}
    </LanguageContext.Provider>
  );
};
